/**
 * Quality gate (QG) runner — single agent invocation at COMPLETE.
 *
 * Runs exactly ONCE per Ralph invocation, after the iteration loop has
 * emitted the completion signal. Reviews the full PR diff (NOT one
 * iteration's diff), auto-fixes high-severity findings in place,
 * files ambiguous follow-ups as new beads, and rewrites the draft
 * PR's title + body before it's marked ready.
 *
 * The QG agent is spawned in the same worktree cwd as the iteration
 * agents so it can edit files and commit fixes. It's the same agent
 * binary (`claude`) but driven by the user's `/quality-gate` skill.
 *
 * v1 strategy: inline the skill markdown into the QG prompt rather
 * than relying on headless slash-command resolution. The follow-up
 * bead `ralph-wiggum-claude-aic` tracks the limitation.
 */

import { spawn } from "node:child_process";
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { parseBranch } from "./branch.js";
import { runProc } from "./proc.js";
import { streamAgentText } from "./stream.js";

/**
 * Structured output the QG agent MUST emit between the fenced markers
 * so we can parse it deterministically out of the streamed text.
 *
 * The markers are XML-tag-shaped so they survive markdown/JSON formatting
 * inside the body and so a partial stream is easy to detect.
 */
export const QG_OUTPUT_OPEN = "<ralph-qg>";
export const QG_OUTPUT_CLOSE = "</ralph-qg>";

/**
 * Findings the agent surfaces in its structured output. `severity`
 * decides routing: `high` is auto-fixed in-place (agent commits),
 * everything else becomes a follow-up bead.
 */
export type QgSeverity = "high" | "medium" | "low";

export type QgFinding = {
	readonly severity: QgSeverity;
	readonly title: string;
	readonly detail?: string;
};

/**
 * Subject + body for the PR. Subject is 1 sentence; body is 2
 * sentences + optional bullet list of closed beads. NO Ralph metadata
 * (no run-id, no token counts, no "generated by ralph" line) — the
 * PRD explicitly excludes those from the PR body.
 */
export type QgPrCopy = {
	readonly subject: string;
	readonly summary: string;
	readonly closedBeads: ReadonlyArray<string>;
};

export type QgAgentOutput = {
	readonly pr: QgPrCopy;
	readonly followUps: ReadonlyArray<QgFinding>;
};

/**
 * Inputs the QG runner needs from the orchestrator: branch + base
 * for diffing, PR URL to edit, cwd for spawning the agent + running
 * git/gh against the right checkout.
 */
export type QualityGateInput = {
	readonly cwd: string;
	readonly branch: string;
	readonly baseBranch: string;
	readonly prUrl: string;
};

/**
 * Side effects abstracted out so the QG orchestration is unit-testable
 * without spawning a real agent or shelling out to git/gh/bd.
 */
export type QualityGatePorts = {
	/** `git diff <base>..HEAD` in the worktree. */
	readonly captureDiff: (input: QualityGateInput) => Promise<string>;
	/**
	 * Parse bead IDs referenced in commit messages on this branch.
	 * Used to populate the PR body's "closed beads" bullet list and
	 * to seed the QG prompt's context.
	 */
	readonly listTouchedBeads: (
		input: QualityGateInput,
	) => Promise<readonly string[]>;
	/**
	 * Read the active epic's notes (descriptions, comments). Returns
	 * empty string when no active epic resolves — QG still runs with
	 * just the diff in that case.
	 */
	readonly readActiveEpicNotes: () => Promise<{
		readonly id: string | undefined;
		readonly notes: string;
	}>;
	/**
	 * Read every file matched by `.claude/rules/**` so the QG prompt
	 * carries the user's project rules. Returns concatenated contents
	 * — empty string when no rules dir exists.
	 */
	readonly readClaudeRules: () => Promise<string>;
	/**
	 * Spawn the QG agent with the rendered prompt, stream output to
	 * stdout, and return the structured `<ralph-qg>...</ralph-qg>`
	 * block parsed into `QgAgentOutput`. Implementations are responsible
	 * for the headless slash-command resolution fallback.
	 */
	readonly runAgent: (args: {
		readonly cwd: string;
		readonly prompt: string;
	}) => Promise<QgAgentOutput>;
	/**
	 * Stage + commit any in-place fixes the agent made. No-op when the
	 * worktree is clean (agent decided no high-severity fixes were
	 * warranted). Returns true if a commit was created.
	 */
	readonly commitAutoFixes: (input: QualityGateInput) => Promise<boolean>;
	/**
	 * Push the (possibly amended) branch so the gh edit/ready sees the
	 * latest SHA. No-op if there's nothing new to push.
	 */
	readonly pushBranch: (input: QualityGateInput) => Promise<void>;
	/**
	 * File a follow-up bead via `bd create --type=task --parent=<epic>
	 * --label=follow-up`. Returns the created bead's ID.
	 */
	readonly createFollowUpBead: (args: {
		readonly title: string;
		readonly detail: string;
		readonly parentEpic: string | undefined;
	}) => Promise<string>;
	/** `gh pr edit <url> --title <X> --body <Y>` against the worktree. */
	readonly editPr: (args: {
		readonly cwd: string;
		readonly prUrl: string;
		readonly title: string;
		readonly body: string;
	}) => Promise<void>;
};

export type QualityGateReport = {
	readonly prTitle: string;
	readonly prBody: string;
	/** Bead IDs filed for ambiguous findings. */
	readonly followUpBeadIds: ReadonlyArray<string>;
	/** True if the QG agent auto-fixed and committed in place. */
	readonly autoFixCommitted: boolean;
};

/**
 * Run the quality gate once at COMPLETE.
 *
 * Pure orchestration — every side effect is in `ports`. The agent
 * output is the source of truth for title/body/follow-ups; we just
 * format and dispatch.
 */
export async function runQualityGate(
	ports: QualityGatePorts,
	input: QualityGateInput,
): Promise<QualityGateReport> {
	const [diff, touchedBeads, activeEpic, claudeRules] = await Promise.all([
		ports.captureDiff(input),
		ports.listTouchedBeads(input),
		ports.readActiveEpicNotes(),
		ports.readClaudeRules(),
	]);

	const prompt = buildQualityGatePrompt({
		diff,
		touchedBeads,
		activeEpicId: activeEpic.id,
		activeEpicNotes: activeEpic.notes,
		claudeRules,
		baseBranch: input.baseBranch,
		branch: input.branch,
	});

	const agentOut = await ports.runAgent({ cwd: input.cwd, prompt });

	const autoFixCommitted = await ports.commitAutoFixes(input);
	if (autoFixCommitted) {
		await ports.pushBranch(input);
	}

	const followUpBeadIds: string[] = [];
	for (const finding of agentOut.followUps) {
		if (finding.severity === "high") {
			throw new Error(
				"quality gate returned a high-severity follow-up; high findings must be auto-fixed before passing",
			);
		}
		const beadId = await ports.createFollowUpBead({
			title: finding.title,
			detail: finding.detail ?? "",
			parentEpic: activeEpic.id,
		});
		followUpBeadIds.push(beadId);
	}

	const prTitle = derivePrTitle({
		branch: input.branch,
		subject: agentOut.pr.subject,
	});
	const prBody = formatPrBody(agentOut.pr);

	await ports.editPr({
		cwd: input.cwd,
		prUrl: input.prUrl,
		title: prTitle,
		body: prBody,
	});

	return { prTitle, prBody, followUpBeadIds, autoFixCommitted };
}

/**
 * Derive the PR title using the branch's semantic prefix.
 * `feat/foo-bar` → `feat: <subject>`.
 *
 * The trailing slash from `parseBranch().prefix` is stripped — we want
 * `feat:` not `feat/:` in the title.
 */
export function derivePrTitle(args: {
	readonly branch: string;
	readonly subject: string;
}): string {
	const parsed = parseBranch(args.branch);
	const prefix = parsed.prefix.replace(/\/$/, "");
	const subject = args.subject.trim();
	if (subject.length === 0) {
		throw new Error("quality gate produced an empty PR subject");
	}
	// If the agent already prefixed the subject (e.g. emitted "feat: foo"
	// despite the prompt telling it not to), strip the duplicate prefix
	// rather than producing "feat: feat: foo".
	const colonAt = subject.indexOf(":");
	if (colonAt > 0) {
		const head = subject.slice(0, colonAt).trim().toLowerCase();
		if (head === prefix) {
			return `${prefix}: ${subject.slice(colonAt + 1).trim()}`;
		}
	}
	return `${prefix}: ${subject}`;
}

/**
 * Format the PR body: 2-sentence summary then (optionally) a bullet
 * list of closed beads. Excludes Ralph branding/run metadata per the
 * PRD.
 */
export function formatPrBody(pr: QgPrCopy): string {
	const summary = pr.summary.trim();
	if (summary.length === 0) {
		throw new Error("quality gate produced an empty PR summary");
	}
	const parts = [summary];
	if (pr.closedBeads.length > 0) {
		const bullets = pr.closedBeads.map((b) => `- ${b}`).join("\n");
		parts.push(`Closed beads:\n${bullets}`);
	}
	return parts.join("\n\n");
}

/**
 * Build the QG prompt sourcing diff, touched beads, active epic notes,
 * and `.claude/rules/*`. Includes the exact structured-output spec the
 * agent MUST follow so `parseQgAgentOutput` succeeds.
 *
 * The skill body is inlined (v1 fallback path — see follow-up bead
 * `ralph-wiggum-claude-aic`). When/if headless `/quality-gate`
 * resolution works, swap this for a `/quality-gate` invocation and
 * keep the structured-output footer.
 */
export function buildQualityGatePrompt(args: {
	readonly diff: string;
	readonly touchedBeads: ReadonlyArray<string>;
	readonly activeEpicId: string | undefined;
	readonly activeEpicNotes: string;
	readonly claudeRules: string;
	readonly baseBranch: string;
	readonly branch: string;
}): string {
	const touchedBeadsBlock =
		args.touchedBeads.length > 0
			? args.touchedBeads.map((b) => `- ${b}`).join("\n")
			: "(none)";
	const activeEpicBlock =
		args.activeEpicId !== undefined
			? `# Active epic: ${args.activeEpicId}\n\n${args.activeEpicNotes.trim()}`
			: "(no active epic)";
	const claudeRulesBlock =
		args.claudeRules.trim().length > 0 ? args.claudeRules.trim() : "(none)";

	return [
		"You are the Ralph quality gate. Review the full PR diff below against the project's rules,",
		"the active epic's notes, and the list of touched beads. Auto-fix high-severity issues in place",
		"(edit files, the orchestrator will commit). File ambiguous concerns as follow-up beads via the",
		"structured output block.",
		"",
		`# Branch: ${args.branch}  →  base: ${args.baseBranch}`,
		"",
		"# Touched beads",
		touchedBeadsBlock,
		"",
		activeEpicBlock,
		"",
		"# Project rules (.claude/rules/*)",
		claudeRulesBlock,
		"",
		"# PR diff",
		"```diff",
		args.diff.trim(),
		"```",
		"",
		"# Output contract (REQUIRED)",
		"",
		`Emit EXACTLY one block between ${QG_OUTPUT_OPEN} and ${QG_OUTPUT_CLOSE} containing valid JSON:`,
		"",
		QG_OUTPUT_OPEN,
		"{",
		'  "pr": {',
		'    "subject": "<imperative 1-line subject, no prefix>",',
		'    "summary": "<exactly 2 sentences explaining what changed and why>",',
		'    "closedBeads": ["<bead-id>", ...]',
		"  },",
		'  "followUps": [',
		'    { "severity": "medium", "title": "<short>", "detail": "<optional>" }',
		"  ]",
		"}",
		QG_OUTPUT_CLOSE,
		"",
		"DO NOT include Ralph branding, token counts, or run metadata in the summary.",
	].join("\n");
}

/**
 * Extract the `<ralph-qg>...</ralph-qg>` JSON block from the agent's
 * streamed text and validate it. Throws a descriptive error when the
 * block is missing or malformed — the caller surfaces that as a QG
 * failure so the run still produces a (draft) PR for human review.
 */
export function parseQgAgentOutput(streamedText: string): QgAgentOutput {
	const openAt = streamedText.lastIndexOf(QG_OUTPUT_OPEN);
	if (openAt === -1) {
		throw new Error(
			`quality gate output missing required ${QG_OUTPUT_OPEN} block`,
		);
	}
	const closeAt = streamedText.indexOf(
		QG_OUTPUT_CLOSE,
		openAt + QG_OUTPUT_OPEN.length,
	);
	if (closeAt === -1) {
		throw new Error(
			`quality gate output missing closing ${QG_OUTPUT_CLOSE} marker`,
		);
	}
	const raw = streamedText
		.slice(openAt + QG_OUTPUT_OPEN.length, closeAt)
		.trim();
	let parsed: unknown;
	try {
		parsed = JSON.parse(raw);
	} catch (err) {
		const msg = err instanceof Error ? err.message : String(err);
		throw new Error(`quality gate emitted invalid JSON: ${msg}`);
	}
	return coerceQgAgentOutput(parsed);
}

function coerceQgAgentOutput(value: unknown): QgAgentOutput {
	if (!isRecord(value)) {
		throw new Error("quality gate output must be a JSON object");
	}
	const prRaw = value.pr;
	if (!isRecord(prRaw)) {
		throw new Error("quality gate output missing `pr` object");
	}
	const subject = readString(prRaw.subject, "pr.subject");
	const summary = readString(prRaw.summary, "pr.summary");
	const closedBeads = readStringArray(prRaw.closedBeads, "pr.closedBeads");

	const followUpsRaw = value.followUps;
	if (!Array.isArray(followUpsRaw)) {
		throw new Error("quality gate output missing `followUps` array");
	}
	const followUps: QgFinding[] = followUpsRaw.map((entry, i) => {
		if (!isRecord(entry)) {
			throw new Error(`followUps[${i}] must be an object`);
		}
		const severity = entry.severity;
		if (severity !== "high" && severity !== "medium" && severity !== "low") {
			throw new Error(
				`followUps[${i}].severity must be one of high/medium/low (got ${String(severity)})`,
			);
		}
		const title = readString(entry.title, `followUps[${i}].title`);
		const detail =
			entry.detail === undefined
				? undefined
				: readString(entry.detail, `followUps[${i}].detail`);
		return detail === undefined
			? { severity, title }
			: { severity, title, detail };
	});

	return {
		pr: { subject, summary, closedBeads },
		followUps,
	};
}

function readString(value: unknown, path: string): string {
	if (typeof value !== "string") {
		throw new Error(`${path} must be a string`);
	}
	return value;
}

function readStringArray(value: unknown, path: string): string[] {
	if (!Array.isArray(value)) {
		throw new Error(`${path} must be an array of strings`);
	}
	return value.map((v, i) => readString(v, `${path}[${i}]`));
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

/* -------------------------------------------------------------------------- */
/* Default port wiring                                                        */
/* -------------------------------------------------------------------------- */

export type DefaultQualityGatePortsOptions = {
	/** Worktree cwd — git/gh/agent all run here. */
	readonly cwd: string;
	/** Main repo root — `.claude/rules/*` is read from here. */
	readonly repoRoot: string;
};

/** Regex that scrapes bead IDs from commit messages (project prefix style). */
const BEAD_ID_PATTERN = /\b([a-z][a-z0-9-]*-[a-z0-9]{2,8})\b/gi;

/**
 * Wire the QG ports to real git / gh / bd / fs side effects against
 * the supplied worktree cwd + repo root.
 *
 * `bd` lookups are tolerant: if the binary isn't installed, or the
 * commands fail (no epic, no rules dir, etc.) we surface empty data
 * rather than aborting the gate — QG must always produce a PR title
 * + body, even on a barebones host.
 */
export function createDefaultQualityGatePorts(
	opts: DefaultQualityGatePortsOptions,
): QualityGatePorts {
	const { cwd, repoRoot } = opts;

	return {
		captureDiff: async (input) => {
			const { stdout } = await runProc({
				cmd: "git",
				args: ["diff", `${input.baseBranch}..HEAD`],
				cwd,
			});
			return stdout;
		},

		listTouchedBeads: async (input) => {
			const { stdout } = await runProc({
				cmd: "git",
				args: ["log", `${input.baseBranch}..HEAD`, "--format=%B"],
				cwd,
			});
			const seen = new Set<string>();
			for (const match of stdout.matchAll(BEAD_ID_PATTERN)) {
				const id = match[1];
				if (id !== undefined) seen.add(id.toLowerCase());
			}
			return Array.from(seen);
		},

		readActiveEpicNotes: async () => {
			// Best-effort: `bd list --type=epic --status=open --json`.
			// Tolerate a missing/broken `bd` so QG can still run on hosts
			// where beads is optional.
			try {
				const { stdout } = await runProc({
					cmd: "bd",
					args: ["list", "--type=epic", "--status=open", "--json"],
					cwd: repoRoot,
					allowNonZero: true,
				});
				const parsed: unknown = JSON.parse(stdout || "[]");
				if (!Array.isArray(parsed) || parsed.length === 0) {
					return { id: undefined, notes: "" };
				}
				// Pick the first open epic; if multiple, the loader should be
				// extended later (tracked via follow-up bead).
				const first = parsed[0];
				if (!isRecord(first)) return { id: undefined, notes: "" };
				const rawId = first.id;
				const id = typeof rawId === "string" ? rawId : undefined;
				const desc =
					typeof first.description === "string" ? first.description : "";
				return { id, notes: desc };
			} catch {
				return { id: undefined, notes: "" };
			}
		},

		readClaudeRules: async () => {
			const rulesDir = join(repoRoot, ".claude", "rules");
			try {
				return await concatMarkdownTree(rulesDir);
			} catch {
				return "";
			}
		},

		runAgent: async ({ cwd: agentCwd, prompt }) => {
			const text = await spawnQualityGateAgent({ cwd: agentCwd, prompt });
			return parseQgAgentOutput(text);
		},

		commitAutoFixes: async (_input) => {
			const status = await runProc({
				cmd: "git",
				args: ["status", "--porcelain"],
				cwd,
			});
			if (status.stdout.trim().length === 0) return false;
			await runProc({ cmd: "git", args: ["add", "-A"], cwd });
			await runProc({
				cmd: "git",
				args: ["commit", "-m", "chore: quality gate auto-fix"],
				cwd,
			});
			return true;
		},

		pushBranch: async (input) => {
			await runProc({
				cmd: "git",
				args: ["push", "origin", input.branch],
				cwd,
			});
		},

		createFollowUpBead: async (args) => {
			// `bd create --type=task --title <t> --description <d>
			//             [--parent <epic>] --labels follow-up --json`
			// Note: the bd flag is `--labels` (plural, comma-separated),
			// and `--parent` accepts a single issue ID. We pass the epic
			// directly so the new bead is filed as a child task.
			const argv = [
				"create",
				"--type=task",
				"--title",
				args.title,
				"--description",
				args.detail,
				"--labels",
				"follow-up",
				"--json",
			];
			if (args.parentEpic !== undefined) {
				argv.push("--parent", args.parentEpic);
			}
			const { stdout } = await runProc({
				cmd: "bd",
				args: argv,
				cwd: repoRoot,
			});
			const parsed: unknown = JSON.parse(stdout || "{}");
			if (isRecord(parsed) && typeof parsed.id === "string") {
				return parsed.id;
			}
			throw new Error(
				`bd create returned no id (stdout=${stdout.slice(0, 200)})`,
			);
		},

		editPr: async ({ cwd: ghCwd, prUrl, title, body }) => {
			await runProc({
				cmd: "gh",
				args: ["pr", "edit", prUrl, "--title", title, "--body", body],
				cwd: ghCwd,
			});
		},
	};
}

/**
 * Recursively concatenate every `*.md` file under `dir` into a single
 * string, prefixed with the relative path so the QG agent knows which
 * rule came from where. Returns empty when the dir is missing.
 */
async function concatMarkdownTree(dir: string): Promise<string> {
	const parts: string[] = [];
	await walk(dir, dir, parts);
	return parts.join("\n\n");
}

async function walk(
	root: string,
	current: string,
	out: string[],
): Promise<void> {
	const entries = await readdir(current, { withFileTypes: true });
	for (const entry of entries) {
		const full = join(current, entry.name);
		if (entry.isDirectory()) {
			await walk(root, full, out);
			continue;
		}
		if (!entry.name.endsWith(".md")) continue;
		const rel = full.slice(root.length + 1);
		const body = await readFile(full, "utf8");
		out.push(`## ${rel}\n\n${body.trim()}`);
	}
}

/**
 * Hard wall-clock cap on a single QG agent invocation. Matches the
 * default per-iteration timeout so a hung quality gate doesn't outlive
 * the budget the user implicitly granted to any one agent call.
 */
const QG_AGENT_TIMEOUT_MS = 30 * 60_000;
const QG_HARD_KILL_GRACE_MS = 5_000;

/**
 * Spawn the Claude Code CLI in headless mode, send the rendered QG
 * prompt on stdin, stream-parse its assistant text, and resolve with
 * the full concatenated text so `parseQgAgentOutput` can pull the
 * structured block out of it.
 *
 * v1 strategy: pass the prompt as the positional `-p <prompt>` arg so
 * we don't depend on slash-command resolution working in headless mode.
 * The user's `/quality-gate` skill is inlined into the prompt by
 * `buildQualityGatePrompt`. Follow-up bead `ralph-wiggum-claude-aic`
 * tracks switching to native slash-command resolution if/when it
 * stabilises in headless `claude`.
 *
 * The spawn carries a hard timeout (mirrors per-iteration timeout) so
 * a hung QG agent can't strand the whole invocation.
 */
function spawnQualityGateAgent(args: {
	readonly cwd: string;
	readonly prompt: string;
}): Promise<string> {
	return new Promise((resolve, reject) => {
		// Stream the prompt via stdin rather than argv — the prompt embeds the
		// full PR diff and a long diff could exceed the OS argv limit (E2BIG)
		// before claude even runs. Claude headless reads stdin when -p has no
		// value (cap ~10MB per docs).
		const child = spawn(
			"claude",
			[
				"-p",
				"--output-format",
				"stream-json",
				"--verbose",
				"--dangerously-skip-permissions",
			],
			{ cwd: args.cwd, stdio: ["pipe", "pipe", "inherit"] },
		);
		child.stdin?.end(args.prompt);

		const stdout = child.stdout;
		if (stdout === null) {
			reject(new Error("quality gate agent produced no stdout"));
			return;
		}

		let collected = "";
		let settled = false;
		let timedOut = false;
		let timer: NodeJS.Timeout | null = null;
		let hardKillTimer: NodeJS.Timeout | null = null;

		const clearTimers = () => {
			if (timer !== null) clearTimeout(timer);
			if (hardKillTimer !== null) clearTimeout(hardKillTimer);
		};
		const safeResolve = (value: string) => {
			if (settled) return;
			settled = true;
			clearTimers();
			resolve(value);
		};
		const safeReject = (err: Error) => {
			if (settled) return;
			settled = true;
			clearTimers();
			reject(err);
		};

		timer = setTimeout(() => {
			timedOut = true;
			child.kill("SIGTERM");
			hardKillTimer = setTimeout(() => {
				child.kill("SIGKILL");
			}, QG_HARD_KILL_GRACE_MS);
		}, QG_AGENT_TIMEOUT_MS);

		const sink: NodeJS.WritableStream = {
			write(chunk: string | Uint8Array): boolean {
				const text =
					typeof chunk === "string"
						? chunk
						: Buffer.from(chunk).toString("utf8");
				collected += text;
				process.stdout.write(text);
				return true;
			},
			end(): void {
				/* no-op */
			},
		} as unknown as NodeJS.WritableStream;

		const streaming = streamAgentText(stdout, sink);

		child.on("error", safeReject);
		child.on("close", (code, signal) => {
			streaming
				.then(() => {
					if (timedOut) {
						safeReject(
							new Error(
								`quality gate agent timed out after ${Math.round(
									QG_AGENT_TIMEOUT_MS / 60_000,
								)} minutes`,
							),
						);
						return;
					}
					if (signal !== null) {
						safeReject(
							new Error(`quality gate agent terminated by signal ${signal}`),
						);
						return;
					}
					if (code !== 0 && code !== null) {
						safeReject(
							new Error(`quality gate agent exited with code ${code}`),
						);
						return;
					}
					safeResolve(collected);
				})
				.catch(safeReject);
		});
	});
}
