/**
 * Quality gate (QG) runner — single agent invocation at COMPLETE.
 *
 * Runs exactly ONCE per Ralph invocation, after the iteration loop has
 * emitted the completion signal. Reviews the full PR diff (NOT one
 * iteration's diff), auto-fixes high-severity findings in place,
 * files ambiguous follow-ups as new beads, and rewrites the draft
 * PR's title + body before it's marked ready.
 *
 * The QG agent is spawned in the same worktree cwd as the iteration
 * agents so it can edit files and commit fixes. It's the same agent
 * binary (`claude`) but driven by the user's `/quality-gate` skill.
 *
 * v1 strategy: inline the skill markdown into the QG prompt rather
 * than relying on headless slash-command resolution. The follow-up
 * bead `ralph-wiggum-claude-qgs` tracks the limitation.
 */

import { parseBranch } from "./branch.js";

/**
 * Structured output the QG agent MUST emit between the fenced markers
 * so we can parse it deterministically out of the streamed text.
 *
 * The markers are XML-tag-shaped so they survive markdown/JSON formatting
 * inside the body and so a partial stream is easy to detect.
 */
export const QG_OUTPUT_OPEN = "<ralph-qg>";
export const QG_OUTPUT_CLOSE = "</ralph-qg>";

/**
 * Findings the agent surfaces in its structured output. `severity`
 * decides routing: `high` is auto-fixed in-place (agent commits),
 * everything else becomes a follow-up bead.
 */
export type QgSeverity = "high" | "medium" | "low";

export type QgFinding = {
	readonly severity: QgSeverity;
	readonly title: string;
	readonly detail?: string;
};

/**
 * Subject + body for the PR. Subject is 1 sentence; body is 2
 * sentences + optional bullet list of closed beads. NO Ralph metadata
 * (no run-id, no token counts, no "generated by ralph" line) — the
 * PRD explicitly excludes those from the PR body.
 */
export type QgPrCopy = {
	readonly subject: string;
	readonly summary: string;
	readonly closedBeads: ReadonlyArray<string>;
};

export type QgAgentOutput = {
	readonly pr: QgPrCopy;
	readonly followUps: ReadonlyArray<QgFinding>;
};

/**
 * Inputs the QG runner needs from the orchestrator: branch + base
 * for diffing, PR URL to edit, cwd for spawning the agent + running
 * git/gh against the right checkout.
 */
export type QualityGateInput = {
	readonly cwd: string;
	readonly branch: string;
	readonly baseBranch: string;
	readonly prUrl: string;
};

/**
 * Side effects abstracted out so the QG orchestration is unit-testable
 * without spawning a real agent or shelling out to git/gh/bd.
 */
export type QualityGatePorts = {
	/** `git diff <base>..HEAD` in the worktree. */
	readonly captureDiff: (input: QualityGateInput) => Promise<string>;
	/**
	 * Parse bead IDs referenced in commit messages on this branch.
	 * Used to populate the PR body's "closed beads" bullet list and
	 * to seed the QG prompt's context.
	 */
	readonly listTouchedBeads: (
		input: QualityGateInput,
	) => Promise<readonly string[]>;
	/**
	 * Read the active epic's notes (descriptions, comments). Returns
	 * empty string when no active epic resolves — QG still runs with
	 * just the diff in that case.
	 */
	readonly readActiveEpicNotes: () => Promise<{
		readonly id: string | undefined;
		readonly notes: string;
	}>;
	/**
	 * Read every file matched by `.claude/rules/**` so the QG prompt
	 * carries the user's project rules. Returns concatenated contents
	 * — empty string when no rules dir exists.
	 */
	readonly readClaudeRules: () => Promise<string>;
	/**
	 * Spawn the QG agent with the rendered prompt, stream output to
	 * stdout, and return the structured `<ralph-qg>...</ralph-qg>`
	 * block parsed into `QgAgentOutput`. Implementations are responsible
	 * for the headless slash-command resolution fallback.
	 */
	readonly runAgent: (args: {
		readonly cwd: string;
		readonly prompt: string;
	}) => Promise<QgAgentOutput>;
	/**
	 * Stage + commit any in-place fixes the agent made. No-op when the
	 * worktree is clean (agent decided no high-severity fixes were
	 * warranted). Returns true if a commit was created.
	 */
	readonly commitAutoFixes: (input: QualityGateInput) => Promise<boolean>;
	/**
	 * Push the (possibly amended) branch so the gh edit/ready sees the
	 * latest SHA. No-op if there's nothing new to push.
	 */
	readonly pushBranch: (input: QualityGateInput) => Promise<void>;
	/**
	 * File a follow-up bead via `bd create --type=task --parent=<epic>
	 * --label=follow-up`. Returns the created bead's ID.
	 */
	readonly createFollowUpBead: (args: {
		readonly title: string;
		readonly detail: string;
		readonly parentEpic: string | undefined;
	}) => Promise<string>;
	/** `gh pr edit <url> --title <X> --body <Y>` against the worktree. */
	readonly editPr: (args: {
		readonly cwd: string;
		readonly prUrl: string;
		readonly title: string;
		readonly body: string;
	}) => Promise<void>;
};

export type QualityGateReport = {
	readonly prTitle: string;
	readonly prBody: string;
	/** Bead IDs filed for ambiguous findings. */
	readonly followUpBeadIds: ReadonlyArray<string>;
	/** True if the QG agent auto-fixed and committed in place. */
	readonly autoFixCommitted: boolean;
};

/**
 * Run the quality gate once at COMPLETE.
 *
 * Pure orchestration — every side effect is in `ports`. The agent
 * output is the source of truth for title/body/follow-ups; we just
 * format and dispatch.
 */
export async function runQualityGate(
	ports: QualityGatePorts,
	input: QualityGateInput,
): Promise<QualityGateReport> {
	const [diff, touchedBeads, activeEpic, claudeRules] = await Promise.all([
		ports.captureDiff(input),
		ports.listTouchedBeads(input),
		ports.readActiveEpicNotes(),
		ports.readClaudeRules(),
	]);

	const prompt = buildQualityGatePrompt({
		diff,
		touchedBeads,
		activeEpicId: activeEpic.id,
		activeEpicNotes: activeEpic.notes,
		claudeRules,
		baseBranch: input.baseBranch,
		branch: input.branch,
	});

	const agentOut = await ports.runAgent({ cwd: input.cwd, prompt });

	const autoFixCommitted = await ports.commitAutoFixes(input);
	if (autoFixCommitted) {
		await ports.pushBranch(input);
	}

	const followUpBeadIds: string[] = [];
	for (const finding of agentOut.followUps) {
		const beadId = await ports.createFollowUpBead({
			title: finding.title,
			detail: finding.detail ?? "",
			parentEpic: activeEpic.id,
		});
		followUpBeadIds.push(beadId);
	}

	const prTitle = derivePrTitle({
		branch: input.branch,
		subject: agentOut.pr.subject,
	});
	const prBody = formatPrBody(agentOut.pr);

	await ports.editPr({
		cwd: input.cwd,
		prUrl: input.prUrl,
		title: prTitle,
		body: prBody,
	});

	return { prTitle, prBody, followUpBeadIds, autoFixCommitted };
}

/**
 * Derive the PR title using the branch's semantic prefix.
 * `feat/foo-bar` → `feat: <subject>`.
 *
 * The trailing slash from `parseBranch().prefix` is stripped — we want
 * `feat:` not `feat/:` in the title.
 */
export function derivePrTitle(args: {
	readonly branch: string;
	readonly subject: string;
}): string {
	const parsed = parseBranch(args.branch);
	const prefix = parsed.prefix.replace(/\/$/, "");
	const subject = args.subject.trim();
	if (subject.length === 0) {
		throw new Error("quality gate produced an empty PR subject");
	}
	// If the agent already prefixed the subject (e.g. emitted "feat: foo"
	// despite the prompt telling it not to), strip the duplicate prefix
	// rather than producing "feat: feat: foo".
	const colonAt = subject.indexOf(":");
	if (colonAt > 0) {
		const head = subject.slice(0, colonAt).trim().toLowerCase();
		if (head === prefix) {
			return `${prefix}: ${subject.slice(colonAt + 1).trim()}`;
		}
	}
	return `${prefix}: ${subject}`;
}

/**
 * Format the PR body: 2-sentence summary then (optionally) a bullet
 * list of closed beads. Excludes Ralph branding/run metadata per the
 * PRD.
 */
export function formatPrBody(pr: QgPrCopy): string {
	const summary = pr.summary.trim();
	if (summary.length === 0) {
		throw new Error("quality gate produced an empty PR summary");
	}
	const parts = [summary];
	if (pr.closedBeads.length > 0) {
		const bullets = pr.closedBeads.map((b) => `- ${b}`).join("\n");
		parts.push(`Closed beads:\n${bullets}`);
	}
	return parts.join("\n\n");
}

/**
 * Build the QG prompt sourcing diff, touched beads, active epic notes,
 * and `.claude/rules/*`. Includes the exact structured-output spec the
 * agent MUST follow so `parseQgAgentOutput` succeeds.
 *
 * The skill body is inlined (v1 fallback path — see follow-up bead
 * `ralph-wiggum-claude-qgs`). When/if headless `/quality-gate`
 * resolution works, swap this for a `/quality-gate` invocation and
 * keep the structured-output footer.
 */
export function buildQualityGatePrompt(args: {
	readonly diff: string;
	readonly touchedBeads: ReadonlyArray<string>;
	readonly activeEpicId: string | undefined;
	readonly activeEpicNotes: string;
	readonly claudeRules: string;
	readonly baseBranch: string;
	readonly branch: string;
}): string {
	const touchedBeadsBlock =
		args.touchedBeads.length > 0
			? args.touchedBeads.map((b) => `- ${b}`).join("\n")
			: "(none)";
	const activeEpicBlock =
		args.activeEpicId !== undefined
			? `# Active epic: ${args.activeEpicId}\n\n${args.activeEpicNotes.trim()}`
			: "(no active epic)";
	const claudeRulesBlock =
		args.claudeRules.trim().length > 0 ? args.claudeRules.trim() : "(none)";

	return [
		"You are the Ralph quality gate. Review the full PR diff below against the project's rules,",
		"the active epic's notes, and the list of touched beads. Auto-fix high-severity issues in place",
		"(edit files, the orchestrator will commit). File ambiguous concerns as follow-up beads via the",
		"structured output block.",
		"",
		`# Branch: ${args.branch}  →  base: ${args.baseBranch}`,
		"",
		"# Touched beads",
		touchedBeadsBlock,
		"",
		activeEpicBlock,
		"",
		"# Project rules (.claude/rules/*)",
		claudeRulesBlock,
		"",
		"# PR diff",
		"```diff",
		args.diff.trim(),
		"```",
		"",
		"# Output contract (REQUIRED)",
		"",
		`Emit EXACTLY one block between ${QG_OUTPUT_OPEN} and ${QG_OUTPUT_CLOSE} containing valid JSON:`,
		"",
		QG_OUTPUT_OPEN,
		"{",
		'  "pr": {',
		'    "subject": "<imperative 1-line subject, no prefix>",',
		'    "summary": "<exactly 2 sentences explaining what changed and why>",',
		'    "closedBeads": ["<bead-id>", ...]',
		"  },",
		'  "followUps": [',
		'    { "severity": "medium", "title": "<short>", "detail": "<optional>" }',
		"  ]",
		"}",
		QG_OUTPUT_CLOSE,
		"",
		"DO NOT include Ralph branding, token counts, or run metadata in the summary.",
	].join("\n");
}

/**
 * Extract the `<ralph-qg>...</ralph-qg>` JSON block from the agent's
 * streamed text and validate it. Throws a descriptive error when the
 * block is missing or malformed — the caller surfaces that as a QG
 * failure so the run still produces a (draft) PR for human review.
 */
export function parseQgAgentOutput(streamedText: string): QgAgentOutput {
	const openAt = streamedText.lastIndexOf(QG_OUTPUT_OPEN);
	if (openAt === -1) {
		throw new Error(
			`quality gate output missing required ${QG_OUTPUT_OPEN} block`,
		);
	}
	const closeAt = streamedText.indexOf(
		QG_OUTPUT_CLOSE,
		openAt + QG_OUTPUT_OPEN.length,
	);
	if (closeAt === -1) {
		throw new Error(
			`quality gate output missing closing ${QG_OUTPUT_CLOSE} marker`,
		);
	}
	const raw = streamedText
		.slice(openAt + QG_OUTPUT_OPEN.length, closeAt)
		.trim();
	let parsed: unknown;
	try {
		parsed = JSON.parse(raw);
	} catch (err) {
		const msg = err instanceof Error ? err.message : String(err);
		throw new Error(`quality gate emitted invalid JSON: ${msg}`);
	}
	return coerceQgAgentOutput(parsed);
}

function coerceQgAgentOutput(value: unknown): QgAgentOutput {
	if (!isRecord(value)) {
		throw new Error("quality gate output must be a JSON object");
	}
	const prRaw = value.pr;
	if (!isRecord(prRaw)) {
		throw new Error("quality gate output missing `pr` object");
	}
	const subject = readString(prRaw.subject, "pr.subject");
	const summary = readString(prRaw.summary, "pr.summary");
	const closedBeads = readStringArray(prRaw.closedBeads, "pr.closedBeads");

	const followUpsRaw = value.followUps;
	if (!Array.isArray(followUpsRaw)) {
		throw new Error("quality gate output missing `followUps` array");
	}
	const followUps: QgFinding[] = followUpsRaw.map((entry, i) => {
		if (!isRecord(entry)) {
			throw new Error(`followUps[${i}] must be an object`);
		}
		const severity = entry.severity;
		if (severity !== "high" && severity !== "medium" && severity !== "low") {
			throw new Error(
				`followUps[${i}].severity must be one of high/medium/low (got ${String(severity)})`,
			);
		}
		const title = readString(entry.title, `followUps[${i}].title`);
		const detail =
			entry.detail === undefined
				? undefined
				: readString(entry.detail, `followUps[${i}].detail`);
		return detail === undefined
			? { severity, title }
			: { severity, title, detail };
	});

	return {
		pr: { subject, summary, closedBeads },
		followUps,
	};
}

function readString(value: unknown, path: string): string {
	if (typeof value !== "string") {
		throw new Error(`${path} must be a string`);
	}
	return value;
}

function readStringArray(value: unknown, path: string): string[] {
	if (!Array.isArray(value)) {
		throw new Error(`${path} must be an array of strings`);
	}
	return value.map((v, i) => readString(v, `${path}[${i}]`));
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}
