import { describe, expect, it, vi } from "vitest";
import {
	type QgAgentOutput,
	type QualityGatePorts,
	runQualityGate,
} from "../quality-gate.js";

function makePorts(
	overrides: Partial<QualityGatePorts> = {},
): QualityGatePorts {
	return {
		command: "/quality-gate",
		captureDiff: vi.fn(async () => "diff --git a/x b/x"),
		listTouchedBeads: vi.fn(async () => ["ralph-wiggum-claude-u61"]),
		readActiveEpicNotes: vi.fn(async () => ({
			id: "ralph-wiggum-claude-a84",
			notes: "Ralph v1 epic notes",
		})),
		readClaudeRules: vi.fn(async () => "## rules.md\n\nbe pragmatic"),
		runAgent: vi.fn(async () => ({
			pr: {
				subject: "wire the quality gate at COMPLETE",
				summary:
					"Add a single end-of-run gate. It rewrites the PR title/body and files follow-ups.",
				closedBeads: ["ralph-wiggum-claude-u61"],
			},
			followUps: [
				{ severity: "medium", title: "consider headless slash resolution" },
			],
		})) as QualityGatePorts["runAgent"],
		commitAutoFixes: vi.fn(async () => false),
		pushBranch: vi.fn(async () => {}),
		createFollowUpBead: vi.fn(async () => "ralph-wiggum-claude-fol"),
		editPr: vi.fn(async () => {}),
		...overrides,
	};
}

describe("runQualityGate", () => {
	const INPUT = {
		cwd: "/tmp/wt",
		branch: "feat/foo",
		baseBranch: "main",
		prUrl: "https://github.com/x/y/pull/1",
	};

	it("files a follow-up bead per finding with the active epic as parent", async () => {
		const createFollowUpBead = vi.fn(async () => "ralph-wiggum-claude-new");
		const ports = makePorts({ createFollowUpBead });

		const report = await runQualityGate(ports, INPUT);

		expect(createFollowUpBead).toHaveBeenCalledTimes(1);
		expect(createFollowUpBead).toHaveBeenCalledWith({
			title: "consider headless slash resolution",
			detail: "",
			parentEpic: "ralph-wiggum-claude-a84",
		});
		expect(report.followUpBeadIds).toEqual(["ralph-wiggum-claude-new"]);
	});

	it("derives the PR title from the branch prefix and formats the body without Ralph metadata", async () => {
		const editPr = vi.fn(async () => {});
		const ports = makePorts({ editPr });

		const report = await runQualityGate(ports, INPUT);

		expect(report.prTitle).toBe("feat: wire the quality gate at COMPLETE");
		expect(report.prBody).toContain("Closed beads:");
		expect(report.prBody).not.toMatch(/iteration[s]?\s+\d+/i);
		expect(report.prBody).not.toMatch(/\b(tokens?|cost|generated by ralph)\b/i);
		expect(editPr).toHaveBeenCalledWith({
			cwd: "/tmp/wt",
			prUrl: "https://github.com/x/y/pull/1",
			title: report.prTitle,
			body: report.prBody,
		});
	});

	it("pushes the branch after auto-fixes are committed (but not when no fixes)", async () => {
		const pushBranch = vi.fn(async () => {});

		const noFixPorts = makePorts({
			commitAutoFixes: vi.fn(async () => false),
			pushBranch,
		});
		await runQualityGate(noFixPorts, INPUT);
		expect(pushBranch).not.toHaveBeenCalled();

		const fixPushed = vi.fn(async () => {});
		const fixPorts = makePorts({
			commitAutoFixes: vi.fn(async () => true),
			pushBranch: fixPushed,
		});
		const report = await runQualityGate(fixPorts, INPUT);
		expect(fixPushed).toHaveBeenCalledTimes(1);
		expect(report.autoFixCommitted).toBe(true);
	});

	it("propagates an agent failure so orchestrate can leave the PR draft", async () => {
		const ports = makePorts({
			runAgent: vi.fn(async () => {
				throw new Error("agent died");
			}) as QualityGatePorts["runAgent"],
		});
		await expect(runQualityGate(ports, INPUT)).rejects.toThrow(/agent died/);
	});

	it("still files follow-ups with parentEpic=undefined when no active epic resolves", async () => {
		const createFollowUpBead = vi.fn(async () => "x-1");
		const ports = makePorts({
			readActiveEpicNotes: vi.fn(async () => ({ id: undefined, notes: "" })),
			createFollowUpBead,
		});

		await runQualityGate(ports, INPUT);

		expect(createFollowUpBead).toHaveBeenCalledWith({
			title: "consider headless slash resolution",
			detail: "",
			parentEpic: undefined,
		});
	});

	it("forwards an agent output with zero follow-ups without filing beads", async () => {
		const createFollowUpBead = vi.fn(async () => "x-1");
		const agentOut: QgAgentOutput = {
			pr: { subject: "x", summary: "One. Two.", closedBeads: [] },
			followUps: [],
		};
		const ports = makePorts({
			runAgent: vi.fn(async () => agentOut) as QualityGatePorts["runAgent"],
			createFollowUpBead,
		});

		const report = await runQualityGate(ports, INPUT);

		expect(createFollowUpBead).not.toHaveBeenCalled();
		expect(report.followUpBeadIds).toEqual([]);
	});

	it("throws when the agent returns a high-severity follow-up", async () => {
		const createFollowUpBead = vi.fn(async () => "x-1");
		const agentOut: QgAgentOutput = {
			pr: { subject: "x", summary: "One. Two.", closedBeads: [] },
			followUps: [{ severity: "high", title: "auth bypass" }],
		};
		const ports = makePorts({
			runAgent: vi.fn(async () => agentOut) as QualityGatePorts["runAgent"],
			createFollowUpBead,
		});

		await expect(runQualityGate(ports, INPUT)).rejects.toThrow(
			/high-severity/i,
		);
		expect(createFollowUpBead).not.toHaveBeenCalled();
	});
});
